// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"database/sql"

	"github.com/google/uuid"
)

type Category struct {
	ID           string         `json:"id"`
	Name         string         `json:"name"`
	Slug         string         `json:"slug"`
	ImageUrl     sql.NullString `json:"image_url"`
	IsActive     sql.NullBool   `json:"is_active"`
	DisplayOrder int32          `json:"display_order"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	UpdatedAt    sql.NullTime   `json:"updated_at"`
}

type Customer struct {
	ID        uuid.UUID      `json:"id"`
	FirstName sql.NullString `json:"first_name"`
	LastName  sql.NullString `json:"last_name"`
	Email     sql.NullString `json:"email"`
	Phone     sql.NullString `json:"phone"`
	CreatedAt sql.NullTime   `json:"created_at"`
}

type GiftCard struct {
	ID             uuid.UUID      `json:"id"`
	Code           string         `json:"code"`
	InitialBalance string         `json:"initial_balance"`
	CurrentBalance string         `json:"current_balance"`
	Currency       sql.NullString `json:"currency"`
	Status         sql.NullString `json:"status"`
	ExpiryDate     sql.NullTime   `json:"expiry_date"`
	CreatedAt      sql.NullTime   `json:"created_at"`
	UpdatedAt      sql.NullTime   `json:"updated_at"`
}

type GiftCardTransaction struct {
	ID         uuid.UUID     `json:"id"`
	GiftCardID uuid.UUID     `json:"gift_card_id"`
	OrderID    uuid.NullUUID `json:"order_id"`
	Amount     string        `json:"amount"`
	Type       string        `json:"type"`
	CreatedAt  sql.NullTime  `json:"created_at"`
}

type Order struct {
	ID            uuid.UUID      `json:"id"`
	CustomerID    uuid.NullUUID  `json:"customer_id"`
	Status        string         `json:"status"`
	TotalAmount   string         `json:"total_amount"`
	PaymentMethod sql.NullString `json:"payment_method"`
	OrderNumber   int32          `json:"order_number"`
	CreatedAt     sql.NullTime   `json:"created_at"`
	UpdatedAt     sql.NullTime   `json:"updated_at"`
}

type OrderItem struct {
	ID        uuid.UUID `json:"id"`
	OrderID   uuid.UUID `json:"order_id"`
	VariantID uuid.UUID `json:"variant_id"`
	Quantity  int32     `json:"quantity"`
	UnitPrice string    `json:"unit_price"`
	Subtotal  string    `json:"subtotal"`
}

type Product struct {
	ID          string         `json:"id"`
	Name        string         `json:"name"`
	Slug        string         `json:"slug"`
	Description sql.NullString `json:"description"`
	BasePrice   string         `json:"base_price"`
	Category    sql.NullString `json:"category"`
	ImageUrl    sql.NullString `json:"image_url"`
	IsActive    sql.NullBool   `json:"is_active"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type ProductCategory struct {
	ProductID  string `json:"product_id"`
	CategoryID string `json:"category_id"`
}

type ProductImage struct {
	ID        string       `json:"id"`
	ProductID string       `json:"product_id"`
	Url       string       `json:"url"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type ProductVariant struct {
	ID            string         `json:"id"`
	ProductID     string         `json:"product_id"`
	Name          string         `json:"name"`
	Sku           string         `json:"sku"`
	Size          sql.NullString `json:"size"`
	Color         sql.NullString `json:"color"`
	Image         sql.NullString `json:"image"`
	Stock         sql.NullInt32  `json:"stock"`
	StockQuantity sql.NullInt32  `json:"stock_quantity"`
	Active        sql.NullBool   `json:"active"`
	Price         int64          `json:"price"`
	DisplayOrder  int32          `json:"display_order"`
	CreatedAt     sql.NullTime   `json:"created_at"`
	UpdatedAt     sql.NullTime   `json:"updated_at"`
}

type User struct {
	ID           uuid.UUID    `json:"id"`
	Email        string       `json:"email"`
	PasswordHash string       `json:"password_hash"`
	Role         string       `json:"role"`
	CreatedAt    sql.NullTime `json:"created_at"`
	UpdatedAt    sql.NullTime `json:"updated_at"`
}
