// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddProductCategory(ctx context.Context, arg AddProductCategoryParams) error
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	CreateGiftCard(ctx context.Context, arg CreateGiftCardParams) (GiftCard, error)
	CreateGiftCardTransaction(ctx context.Context, arg CreateGiftCardTransactionParams) (GiftCardTransaction, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	// Product Variant Mutations
	CreateProductVariant(ctx context.Context, arg CreateProductVariantParams) (ProductVariant, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteCategory(ctx context.Context, id string) error
	DeleteProduct(ctx context.Context, id uuid.UUID) error
	DeleteProductVariant(ctx context.Context, id string) error
	// Coupons
	CreateCoupon(ctx context.Context, arg CreateCouponParams) (Coupon, error)
	DeleteCoupon(ctx context.Context, id int64) error
	GetCoupon(ctx context.Context, id int64) (Coupon, error)
	GetCouponByCode(ctx context.Context, code string) (Coupon, error)
	ListCoupons(ctx context.Context) ([]Coupon, error)
	UpdateCoupon(ctx context.Context, arg UpdateCouponParams) (Coupon, error)

	// Settings & Users
	GetStoreSettings(ctx context.Context) (StoreSetting, error)
	UpdateStoreSettings(ctx context.Context, arg UpdateStoreSettingsParams) (StoreSetting, error)
	ListAdminUsers(ctx context.Context) ([]ListAdminUsersRow, error)
	CreateAdminUser(ctx context.Context, arg CreateAdminUserParams) (CreateAdminUserRow, error)
	UpdateAdminUser(ctx context.Context, arg UpdateAdminUserParams) (UpdateAdminUserRow, error)
	UpdateAdminPassword(ctx context.Context, arg UpdateAdminPasswordParams) error
	DeleteAdminUser(ctx context.Context, id int64) error

	// Inventory
	CreateInventoryMovement(ctx context.Context, arg CreateInventoryMovementParams) (InventoryMovement, error)
	ListInventoryMovements(ctx context.Context, arg ListInventoryMovementsParams) ([]ListInventoryMovementsRow, error)
	GetLowStockVariants(ctx context.Context, stockQuantity int32) ([]GetLowStockVariantsRow, error)
	GetInventoryStats(ctx context.Context) (GetInventoryStatsRow, error)

	// Analytics
	GetSalesAnalytics(ctx context.Context, arg GetSalesAnalyticsParams) (GetSalesAnalyticsRow, error)
	GetTopSellingProducts(ctx context.Context, arg GetTopSellingProductsParams) ([]GetTopSellingProductsRow, error)
	GetCustomerMetrics(ctx context.Context, arg GetCustomerMetricsParams) (GetCustomerMetricsRow, error)
	GetRevenueByDate(ctx context.Context, arg GetRevenueByDateParams) ([]GetRevenueByDateRow, error)

	GetCategory(ctx context.Context, id string) (Category, error)
	GetCustomer(ctx context.Context, id uuid.UUID) (Customer, error)
	GetCustomerDetails(ctx context.Context, id uuid.UUID) (GetCustomerDetailsRow, error)
	GetGiftCardByCode(ctx context.Context, code string) (GiftCard, error)
	GetOrder(ctx context.Context, id uuid.UUID) (GetOrderRow, error)
	GetProduct(ctx context.Context, id string) (Product, error)
	GetProductVariant(ctx context.Context, id string) (ProductVariant, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	// Categories
	ListCategories(ctx context.Context) ([]Category, error)
	// Customers
	ListCustomers(ctx context.Context) ([]ListCustomersRow, error)
	ListCustomerOrders(ctx context.Context, customerID uuid.NullUUID) ([]ListCustomerOrdersRow, error)
	ListOrderItems(ctx context.Context, orderID uuid.UUID) ([]ListOrderItemsRow, error)
	ListOrders(ctx context.Context) ([]ListOrdersRow, error)
	// Product Categories (Many-to-Many)
	ListProductCategories(ctx context.Context, productID string) ([]Category, error)
	ListProductImages(ctx context.Context, productID string) ([]ProductImage, error)
	AddProductImage(ctx context.Context, arg AddProductImageParams) (ProductImage, error)
	DeleteProductImage(ctx context.Context, id string) error
	CountOrderItemsByProductID(ctx context.Context, productID string) (int64, error)
	DeleteProductPrices(ctx context.Context, productID string) error
	DeleteProductVariants(ctx context.Context, productID string) error
	DeleteProductImagesByProductID(ctx context.Context, productID string) error
	ListProductVariants(ctx context.Context, productID string) ([]ProductVariant, error)
	ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error)
	ListProductsByCategorySlug(ctx context.Context, arg ListProductsByCategorySlugParams) ([]ListProductsRow, error)
	UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error)
	RemoveProductCategory(ctx context.Context, arg RemoveProductCategoryParams) error
	SetProductCategories(ctx context.Context, productID string) error
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error)
	UpdateGiftCardBalance(ctx context.Context, arg UpdateGiftCardBalanceParams) (GiftCard, error)
	UpdateOrder(ctx context.Context, arg UpdateOrderParams) (Order, error)
	// Product Mutations
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error)
	UpdateProductVariant(ctx context.Context, arg UpdateProductVariantParams) (ProductVariant, error)
	UpdateVariantStock(ctx context.Context, arg UpdateVariantStockParams) error
	// Public order lookup
	GetOrderByNumber(ctx context.Context, orderNumber int32) (GetOrderByNumberRow, error)
	ListOrderItemsByOrderNumber(ctx context.Context, orderNumber int32) ([]OrderItemPublic, error)
}

var _ Querier = (*Queries)(nil)
